parameters:
#    acme_business.example.class: Acme\BusinessBundle\Example



services:

#    accounts_service:
#        class: SDRO\AccountBundle\Model\Accounts
#        arguments: [ @doctrine.orm.entity_manager ] 
#        calls:
#             - [setContainer, ["@service_container"]]
        
#    acme.account.admin.account:
#        class: Acme\AccountBundle\Admin\AccountAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Setting", label: "Account" }
#        arguments: [ null, Acme\AccountBundle\Entity\Account, ~ ]
#        calls:
#            - [ setTranslationDomain, [SDROAccountBundle]]  
                 
            
     
 #================> SETTING  <==================== 

    app.acme.account.admin.batch:
        class: SDRO\AccountBundle\Admin\BatchAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Setting", label: "Batch" }
        arguments: [ null, SDRO\AccountBundle\Entity\Batch, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   
            
    app.acme.account.admin.period:
        class: SDRO\AccountBundle\Admin\PeriodAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: "Fiscal Year" }
        arguments: [ null, SDRO\AccountBundle\Entity\Period, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]               
            
    app.acme.account.admin.report:
        class: SDRO\AccountBundle\Admin\ReportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: " Report" }
        arguments: [ null, SDRO\AccountBundle\Entity\Report, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   

    app.acme.account.admin.report_index:
        class: SDRO\AccountBundle\Admin\ReportIndexAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: " Report Index" }
        arguments: [ null, SDRO\AccountBundle\Entity\ReportIndex, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   
            
    app.acme.account.admin.account_head:
        class: SDRO\AccountBundle\Admin\AccountHeadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: " Account Head" }
        arguments: [ null, SDRO\AccountBundle\Entity\AccountHead, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   

    app.acme.account.admin.group:
        class: SDRO\AccountBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: "Group" }
        arguments: [ null, SDRO\AccountBundle\Entity\Group, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   

    app.acme.account.admin.account_group:
        class: SDRO\AccountBundle\Admin\AccountGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: " Account Group" }
        arguments: [ null, SDRO\AccountBundle\Entity\AccountGroup, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   
            
    app.acme.account.admin.account:
        class: SDRO\AccountBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Account Setting", label: "Account" }
        arguments: [ null, SDRO\AccountBundle\Entity\Account, null]  
#        arguments: [null,null,null]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   

#================> ACCOUNT INFO <====================
            
#    acme.account.admin.accounts:
#        class: Acme\AccountBundle\Admin\AccountsAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Accounts Info", label: "Accounts Transaction" }
#        arguments: [ null, Acme\AccountBundle\Entity\Account, SDROAccountBundle:Admin\Accounts ]  
#        calls:
#            - [ setTranslationDomain, [SDROAccountBundle]]   
#            - [ setTemplate, [list, SDROAccountBundle:Account:lists.html.twig]]

    app.acme.account.admin.invoice: 
        class: SDRO\AccountBundle\Admin\InvoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts Info", label: "Invoice" }
        arguments: [ null, SDRO\AccountBundle\Entity\Invoice, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]       

    app.acme.account.admin.ledger:
        class: SDRO\AccountBundle\Admin\LedgerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts Info", label: "Ledger" }
        arguments: [ null, SDRO\AccountBundle\Entity\Ledger, null ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]   

           
      
    app.acme.account.admin.reports:
        class: SDRO\AccountBundle\Admin\ReportsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts Info", label: "Reports" }
        arguments: [ null, SDRO\AccountBundle\Entity\Report, SDROAccountBundle:Admin\Reports ]
        calls:
            - [ setTranslationDomain, [SDROAccountBundle]]
#            - [ setTemplate, [layout, SDROAccountBundle::standard_layout.html.twig]]
            
                          
            
#    acme.account.admin.account:
#        class: Acme\AccountBundle\Admin\LedgerAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Account", label: "Account Info" }
#        arguments:
#            - ~
#            - Acme\AccountBundle\Entity\Ledger
#            - AcmeEducationBundle:Admin\StudentAdmin
#            - SDROAccountBundle:Ledger
#        calls:
#            - [ setTranslationDomain, [SDROAccountBundle]]
#            - [ setTemplate, [list, SDROAccountBundle:Ledger:base_list.html.twig]]
#            - [ setTemplate, [edit, SDROAccountBundle:Ledger:base_edit.html.twig]]
#            - [ setTemplate, [info, SDROAccountBundle:Ledger:list.html.twig]]
            
                   